### ISSUE TITLE
Flipper Zero Testing

### ISSUE THREAD

**Issue by bigbulse** [ecrawford-0/Capstone#10]
Test capabilities of RFID Flipper.

- [x] Read RFID Card
- [x] Write to RFID Card
- [x] Emulate RFID
- [x] Read NFC Card
- [x] Emulate NFC
- [x] Test Mobile App

**Comment by ecrawford-0** [comment]
Preliminary experiments found out that the Flipper can read and emulate NFC, but for Mifare Ultralight it needs to be selected or it won't copy the data over

**Comment by bigbulse** [comment]
Tested all the above tasks. 

Saved an old RFID card and wrote it to the blank RFID 1 Card.

Mobile App is used a companion to the Flipper. Can use it to remote control, edit saved entries, check version and health; that sort of thing.

![image](https://user-images.githubusercontent.com/59936853/200705026-a9a92e25-97b5-414e-9b2d-34a841ad9a37.jpeg)

![image](https://user-images.githubusercontent.com/59936853/200705038-3f06c3f4-f5c2-48e2-8e8a-38cf7ccc2cbd.jpeg)
