### ISSUE TITLE
Defense Testing

### ISSUE THREAD

**Issue by bigbulse** [ecrawford-0/Capstone#12]
Test the capabilities of RFID protection. 

Methodology:  
- Scan Card normally
- Place card in protection
- Attempt scan again
- Repeat for different protection
- If scan successful with protection, repeat at range

**Comment by bigbulse** [comment]
Testing is recorded and complete. Going to take screenshots from the videos and update the testing page.

**Comment by bigbulse** [comment]
https://github.com/ecrawford-0/Capstone/wiki/RFID-Defense-Testing

Results recorded. Awaiting review by @ecrawford-0 
But this issue can be closed.

**Comment by ecrawford-0** [comment]
Defense testing page review complete
