### ISSUE TITLE
Meet with Eastman

### ISSUE THREAD

**Issue by bigbulse** [ecrawford-0/Capstone#17]

**Comment by bigbulse** [comment]
Meeting scheduled for 10/27 @ 9 AM

**Comment by ecrawford-0** [comment]
## Summary/To-dos
- Define what our end goal for both the end of this semester, and for next semester
  - 50% of medical devices are non-compliant, what does this say? 
- Look into 2 frameworks that RFID and NFC should follow/can follow such as(NIST, ISO)
- Find more about the on campus radio station (The Wave)
- Scientific Method for how we want to plan attacks
- Looking into different attacks - at this stage we would do more research/creating hardware list, doing the attacks would be more of a spring semester item 
  - Interception attacks (possibility of looking into how to boost the range of something like the flipper) 
  - Relay attacks 
  - Define other attacks we would pursue
- Demo at the end of this project milestone will be going through progress made.
