### ISSUE TITLE
NFC Range Testing (Tap-To-Pay)

### ISSUE THREAD

**Issue by bigbulse** [ecrawford-0/Capstone#3]
Determine the maximum range of Tap-To-Pay by using a card on NFC reader.

Dependences:
NFC Reader
NFC Card

**Comment by ecrawford-0** [comment]
-- update as of 11/1 we received the NFC reader, tags, and cards, so the amiibo is **not** used for the range testing

**Comment by ecrawford-0** [comment]
-- all testing has been performed and data has been recorded. Only conclusion is needed

**Comment by ecrawford-0** [comment]
-- conclusion finished
