### ISSUE TITLE
Interpret RFID Reader packets

### ISSUE THREAD

**Issue by ecrawford-0** [ecrawford-0/Capstone#50]
Be able to meaningfully interpret and make sense of the data collected.

**Comment by bigbulse** [comment]
These numbers could be Smart card application protocol data units (APDUs). These are used to send commands from the reader and the card.

**Comment by bigbulse** [comment]
![Image](https://user-images.githubusercontent.com/59936853/216835920-9fb98767-26bb-4cf9-9f97-0da1a1595e0b.png)
