### ISSUE TITLE
Capture RFID Reader packets

### ISSUE THREAD

**Issue by ecrawford-0** [ecrawford-0/Capstone#7]
When we read an RFID card the data is displayed on the Flipper in a neat and human readable format. However, this can be viewed raw by using a remote cli command.

Dependences:
FlipperZero
RFID Card
Computer
USBC cable

**Comment by bigbulse** [comment]
Flipper Zero debug mode allows for the raw analysis of RFID data
This can be viewed from the cli 

Flipper Zero tutorials page has been updated with this infromantion
