### ISSUE TITLE
Nexus  Huawei Phone  - Research

### ISSUE THREAD

**Issue by bigbulse** [ecrawford-0/Capstone#73]
Research how to use the Nexus Huawei phone for NFC and how to safely take it apart.

**Comment by ecrawford-0** [comment]
Something of note is that the Nexus phone can turn nfc on or off
https://devicehelp.optus.com.au/huawei/nexus-6p-android-6-0/internet-and-data/turn-nfc-on-or-off/

**Comment by ecrawford-0** [comment]
For teardown we may or may not need some kind of heating device to loosen glue. It will also be extremely difficult if not impossible to not break the back glass 

https://www.youtube.com/watch?v=yHIch_CO330
https://www.ifixit.com/Teardown/Nexus+6P+Teardown/51660
https://www.youtube.com/watch?v=VVIGJCAx-I8

**Comment by bigbulse** [comment]
being able to use NFC tools with the phone opens up a whole new avenue of testing for us such as more verbose NFC reading (like seeing what a vender would see) and additional options provided by the application.

**Comment by ecrawford-0** [comment]
https://github.com/ecrawford-0/Capstone/wiki/Nexus-Huawei-Phone-background-information
