### ISSUE TITLE
Setup environment - RF access controller

### ISSUE THREAD

**Issue by ecrawford-0** [ecrawford-0/Capstone#88]
Setup the environment for testing the RFID access controller

**Comment by ecrawford-0** [comment]
https://github.com/ecrawford-0/Capstone/wiki/RFID-access-control-environment#setup-procedure

**Comment by bigbulse** [comment]
Access Controller environment is setup. 

- Default password: 7890
- Default Programming Password: 881122
- Setup new Card: `*` `881122` `#` `1` *Swipe Card*
- Delete Card: `*` `881122` `#` `4` *swipe card*

**Comment by bigbulse** [comment]
https://github.com/ecrawford-0/Capstone/wiki/RFID-access-control-environment
